services:
  app:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: sys_fin_app
    ports:
      - "9000:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - sys_fin_network
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres_sysfinan_db
      DB_PORT: 5432
      DB_DATABASE: sys_fin_db
      DB_USERNAME: hugo
      DB_PASSWORD: 123
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres_sysfinan_db
    environment:
      POSTGRES_USER: hugo
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sys_fin_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - sys_fin_network

networks:
  sys_fin_network:
    driver: bridge