name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

      - name: Create SSH private key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/sysf.pem
          chmod 600 ~/.ssh/sysf.pem

      - name: Deploy to EC2
        run: |
          ls -l ~/.ssh
          
          ssh -i ~/.ssh/sysf.pem -o StrictHostKeyChecking=no ubuntu@44.220.152.213 << 'EOF'
            cd /home/ubuntu/sys-finan/src
            git pull origin master
            composer install --optimize-autoloader --no-dev
            php artisan key:generate
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
          EOF
