name: Deploy Laravel to Hetzner

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.HETZNER_SSH_PRIVATE_KEY }}

      - name: Deploy to Hetzner
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@167.235.240.206 << 'EOF'
            echo "➡️ Iniciando deploy Laravel no Hetzner"

            cd /home/ubuntu/sys-finan/src

            git fetch --all
            git reset --hard origin/master

            composer install --optimize-autoloader --no-dev --no-interaction

            php artisan migrate --force

            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            chown -R www-data:www-data /home/ubuntu/sys-finan/src

            echo "✅ Deploy finalizado com sucesso"
          EOF
