name: Formats

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.2]
        dependency-version: [prefer-lowest, prefer-stable]

    name: Formats P${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, mbstring, zip
          coverage: pcov

      - name: Get Composer cache directory
        id: composer-cache
        shell: bash
        run: |
          cd src
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Install Composer dependencies
        run: |
          cd src
          composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: Coding Style Checks
        if: matrix.dependency-version != 'prefer-lowest'
        run: |
          cd src
          composer test:lint
